#Crear la variable {{token}} con el token JWT obtenido al hacer login
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwiaWF0IjoxNzY3ODgxNTMzLCJleHAiOjE3Njc4ODUxMzN9.GnCsTAfydrhZNQ5vQo5kAwg_AbJyfAd1OGw7I-54JZU



### Ejemplo de petición con autorización Basic
GET http://localhost:8080/states/1
Authorization: Bearer {{token}}



### Login con usuario y contraseña (form-urlencoded)
POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=12345

