#Crear la variable {{token}} con el token JWT obtenido al hacer login
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzY3Nzk3MDYxLCJleHAiOjE3Njc4MDA2NjF9.BmeB1Sv1MO13fcGzu3R4aYdbMmbMF6NXtZZ7eTvyWYw



### Ejemplo de petición con autorización Basic
GET http://localhost:8080/states/1
Authorization: Bearer {{token}}



### Login con usuario y contraseña (form-urlencoded)
POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=12345

