#Crear la variable {{token}} con el token JWT obtenido al hacer login
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTc2Nzg4NDMyMiwiZXhwIjoxNzY3ODg3OTIyfQ.syBy5f1dFU0R0VfdmA-27BpEMZBZEMnXvIwRSqVym5A



### Ejemplo de petición con autorización Basic
GET http://localhost:8080/states/1
Authorization: Bearer {{token}}



### Login con usuario y contraseña (form-urlencoded)
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "12345"
}

