
### Crear State
POST http://localhost:8080/states
Content-Type: application/json

{
    "stateDescription": "PENDIENTE",
    "stateComment": "Estado inicial de la solicitud"
}

### Obtener State por ID
GET http://localhost:8080/states/1
Authorization: Basic admin:admin


### Actualizar State
PUT http://localhost:8080/states/2
Content-Type: application/json

{
    "stateDescription": "ACTUALIZADO",
    "stateComment": "Estado actualizado de la solicitud"
}

### Eliminar State
DELETE http://localhost:8080/states/2

### Listar todos los States
GET http://localhost:8080/states
Authorization: Basic user:admin

### Listar todos los StatesJpa
GET http://localhost:8080/states/jpa
