@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTc2Nzg4ODE3MiwiZXhwIjoxNzY3ODkxNzcyfQ.CQNYVQQR3GDoef9XWOucYbGF5EqosMTKqSHRao8bsaQ


### Crear State
POST http://localhost:8080/states
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "stateDescription": "EJECUTADO",
    "stateComment": "Estado inicial de la solicitud"
}

### Obtener State por ID
GET http://localhost:8080/states/100
Authorization: Bearer {{token}}


### Actualizar State
PUT http://localhost:8080/states/2
Content-Type: application/json

{
    "stateDescription": "ACTUALIZADO",
    "stateComment": "Estado actualizado de la solicitud"
}

### Eliminar State
DELETE http://localhost:8080/states/2

### Listar todos los States
GET http://localhost:8080/states
Authorization: Basic user:admin

### Listar todos los StatesJpa
GET http://localhost:8080/states/jpa


### Listar todos los States desde procedimiento almacenado
GET http://localhost:8080/states/procedure
Authorization: Bearer {{token}}

### Listar todos los States desde procedimiento almacenado con repository
GET http://localhost:8080/states/procedure-repository
Authorization: Bearer {{token}}
